# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install Protoc
      run: |
        sudo apt-get update -q
        sudo apt-get install -y protobuf
        chmod +x protoc-gen-go
        sudo mv protoc-gen-go /usr/local/bin/

    - name: Install Dev Tools
      run: make dev_tool

    - name: Generate Protocols
      run: make gen_natsrpc && make gen_proto && make gen_client_proto

    - name: Build
      run: make build
